### ISSUE TITLE
comments from MoveApps

### ISSUE THREAD

**Issue by andreakoelzsch** [vee-jain/WeeklyKDE-MoveApps#1]
Dear vee-jain,

Thanks a lot for your contribution to our MoveApps EMAC coding challenge!

I have looked through your files, but am not able to build the App for MoveApps integration, as there are a few issues that you have to fix. Please address them and then submit a new App version to MoveApps (related to a new release on this repository).

1) You have not adapted the file appspec.json to your App. Here, you have to enter the details for settings you let the user make (none, as I see from your RFunction.R), list all the R packages that are needed for your App, set artifacts to true, select your open source license, add some keywords so people can find your App, add your details as author and (very important!) copy the path to your readme.md in the repository). See also our user manual, there is a settings editor that allows check if your appspec.json is correct. https://docs.moveapps.org/#/appspec 
2) Please return in your RFuntion the input data set at the end (return(data)) so that the App can be entered into a workflow the might be continued. Of course, you can also decide to pass on only a part of the data set (all data within the KDEs), but it needs to be a MoveStack for now.
3) Note that the paths for files/artefacts to save need to be special in MoveApps so that they end up in the correct locations for the user to download. Please use our build in function like this example:  write.csv(your_table,appArtifactPath("your_file_name.csv"),row.names=FALSE)

All the best, Andrea (MoveApps)

**Comment by vee-jain** [comment]
Dear Andrea,

Thank you very much for your feedback. I have submitted an updated version of the app on MoveApps. Please let me know if there are any more issues.

Best wishes,
Varalika

**Comment by andreakoelzsch** [comment]
HI Varalika, the APp is now built successfully on MoveAPps, please test there if it behaves as expected. Thanks! Andrea

**Comment by vee-jain** [comment]
Hi Andrea, I noticed that the App post-processing time is taking a while and I am only able to see the .rds output on the platform. Any idea why that might be the case?

**Comment by andreakoelzsch** [comment]
HI Varalika, ja, ich sehe auch das lange post-processing. Schau mal in die Logs (drei-Punkte Menu in der App), dann siehst du, dass es viele Warnings der Art `stat_bin()` using `bins = 30`. Pick better value with `binwidth` gibt. Lokal bekomme auch auch immer diese Warnings. BItte hast du mir evtl ein input-Datensatz, der durchläuft? Einfach die rds per Email an mich oder hier einstellen. Ich sehe, dass die App sehr viele Artefakte hat, aber das sollte grundsätzlich kein Problem sein.

**Comment by andreakoelzsch** [comment]
Vieleicht macht es doch sinn, dem User ein paar Parameter zu geben? Du hast viele Zahlen fix im Code, die vielleicht bei anderen Datzensätzen so nicht passen? Aber das könnte man auch später noch fixen. Jetzt erstmal das so zum Laufen bringen. Danke

**Comment by andreakoelzsch** [comment]
Hi Varalika @vee-jain, sorry, do you understand German? I only now realise that I had not written the messages for you in English, sorry! Please would you send me an input file for your App that does work? Maybe the one that you have used for developing and that is noted in the co-pilot.R file?

**Comment by vee-jain** [comment]
Hi Andrea, sorry I don't understand German, no worries at all. I used the 4 input files in the Hello World example/ template (input1_greylgeese and so on) to test it out. I do see the errors with the graphic parameters - the plots are still made but you're right, I would like to improve the code such that the user can make changes as per their requirements :) Let me know if it works for you to run these files and if I should email them to you. Thanks for all your help!

**Comment by andreakoelzsch** [comment]
Hi Varalika,
I got your App working locally, very nice output files, thanks! I am not sure why it does not finish the postprocessing on MoveApps. It is by far the App with the largest number of artefacts ever, so maybe that is a problem. I can only check that and some other details on Monday with our developer. I will let you know about it then, but the App looks fine so far. I will give some feedback about it then and we see how to proceed. Happy weekend and good luck with your eagles.
Andrea

**Comment by vee-jain** [comment]
Hi Andrea,
Thanks so much for the feedback! I think another option, and perhaps a bit more versatile one for users, could be to break down the app into individual smaller apps that can be linked together in a workflow. 
Have a lovely weekend!

**Comment by andreakoelzsch** [comment]
That is definitely a great idea! Lets chat about it on Tuesday. Merci

**Comment by andreakoelzsch** [comment]
Hi @vee-jain, I have talked with our developer about your app and why the artefacts dont come through. There is an error that is caused by the fact that MoveApps cannot grap folders as artefacts and you are making folders for the html files. Since the folders cannot be downloaded, it gets stuck and also does not load the other files. You can solve this in teh following way: Make the folder and html for each track (an other things) into zip files (do that within a temp folder) and save the zip file in the artefact folder. See below some example code for zipping shapefiles. Just so you can get an idea... Please try it out and we can talk also about it tomorrow.
See you, Andrea

````
dir.create(targetDirShapeFiles <- tempdir())
#targetDirShapeFiles <- paste0(targetDirShapeFiles,"/",file.name)
# enter here your code for creating html for an individual
#writeOGR(data.spdf,dsn=targetDirShapeFiles,layer=file.name,driver="ESRI Shapefile",overwrite_layer=TRUE)
  zip::zip(
    zipfile=appArtifactPath("output.zip"),
    files=  targetDirShapeFiles,
    mode = "cherry-pick"
  )
````

**Comment by vee-jain** [comment]
Thank you for the feedback - let me see if I can eliminate the folders all together... otherwise I'll try the .zip solution! Talking about it tomorrow sounds like a good idea :)

**Comment by vee-jain** [comment]
Hi Andrea,

I've updated the code with the .zip function! I hope that runs without issues now. Thanks for your help with understanding how to do it!

**Comment by andreakoelzsch** [comment]
Hi Varalika, I have just been able to build your new App version and it runs on MoveApps! Congratulations! Then I can include it in the batch of workflows and send them to review for the challenge committee. Perfect. Thanks for your contribution and interest to be involved with MoveApps. Looking forward to the next time. Best, Andrea
